#!/bin/bash
#
# Simple shell script to make your life so much easier by not having to type the meteor run command everytime.

echo -e "Starting the almighty SpaceTalk using the default settings.json file"

exec meteor run --settings settings.json
